version: 2.1.0.{build}

configuration: Release

image: Visual Studio 2017
branches:
  only:
  - master
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./SampleAPI/CSharp/Tasks/TaskFly.Integra/TaskFly.Integra.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./SampleAPI/CSharp/Tasks/TaskFly.Integra/TaskFly.Integra.csproj -o ./SampleAPI/CSharp/Tasks/TaskFly.Integra/publish

artifacts:
  - path: ./SampleAPI/CSharp/Tasks/TaskFly.Integra
    name: publish

deploy:
- provider: NuGet
  api_key:
    secure: 7dmlOrRS5rDSxgwuxJCrtPXY4kaxX+6N95JtvAdyvjCeoUXXt20i4nmuKIcAS2jd
  skip_symbols: true
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  subject: TaskFly.Integra  Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
  
