version: 1.0.0.{build}

configuration: Release

image: Visual Studio 2017
branches:
  only:
  - master

assembly_info:  
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - cmd: dotnet restore ./SampleAPI/CSharp/Tasks/TaskFly.Integra/TaskFly.Integra.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./SampleAPI/CSharp/Tasks/TaskFly.Integra/TaskFly.Integra.csproj -o ./SampleAPI/CSharp/Tasks/TaskFly.Integra/publish
  - cmd: nuget pack ./SampleAPI/CSharp/Tasks/TaskFly.Integra/TaskFly.Integra.nuspec -version %appveyor_build_version%
artifacts:
  - path: ./SampleAPI/CSharp/Tasks/TaskFly.Integra/*.nupkg
    name: publish

deploy:
- provider: NuGet
  api_key:
    secure: 7dmlOrRS5rDSxgwuxJCrtPXY4kaxX+6N95JtvAdyvjCeoUXXt20i4nmuKIcAS2jd
  skip_symbols: true
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  subject: TaskFly.Integra  Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
  
